name = "MtkLibrary"
uuid = "a0ce3b87-3962-4a0a-8f14-cd2409246f96"
authors = ["Sarath Suresh"]
version = "1.0.0-DEV"

[compat]
julia = "1.9.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
